version: "3.7"
services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
